# Generated by Django 3.2.8 on 2022-01-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='rating',
        ),
        migrations.AddField(
            model_name='contact',
            name='rate_us',
            field=models.CharField(blank=True, choices=[('1', ' '), ('2', ' '), ('3', ' '), ('4', ' '), ('5', ' ')], max_length=6, null=True),
        ),
    ]
