# Generated by Django 3.2.8 on 2022-02-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220127_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='rate_us',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=6, null=True),
        ),
    ]
