""" Import required for app configuration """
from django.apps import AppConfig


class CheckoutConfig(AppConfig):
    """ Automatically generated by django """
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'checkout'

    def ready(self):
        """ import checkout.signals """
        import checkout.signals
