""" Import required for app configuration """
from django.apps import AppConfig


class ProductsConfig(AppConfig):
    """ Automatically generated by django """
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'products'
