# Generated by Django 3.2.8 on 2021-12-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211218_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyl',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vinyl',
            name='stock_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vinyl',
            name='track_list',
            field=models.TextField(default='Add in tracklist e.g 1. Track Title'),
        ),
    ]
